### ISSUE TITLE
[Feat]:Independent User Group Application

### ISSUE THREAD

**Issue by ryoakirasan** [lowcoder-org/lowcoder#231]
**Is your feature request related to a problem? Please describe.**
Each user group can have their own user homepage application. If there are multiple user groups, switching between multiple applications is possible.

If a default homepage application has already been set in the advanced settings, it will be displayed and switched together. If no default homepage application is set in the advanced settings by default, users under each user group can enter their own homepage application.

**Describe the solution you'd like**
**Task**
- [ ] Can set a homepage application for each user group
- [ ] The Java backend interface saves the user group application settings
- [ ] Multiple user group application switching page

**Comment by FalkWolsky** [comment]
Very nice feature!

**Comment by ryoakirasan** [comment]
https://github.com/lowcoder-org/lowcoder/issues/261
I can't do backend testing because of this issue
